import type { Metadata } from "next";
import { ArrowUpRight, MapPin } from "lucide-react";
import { ActionLink, CallToAction, Eyebrow, PageIntro } from "@/components/portfolio/Primitives";
import { journey, person } from "@/data/portfolio";
export const metadata: Metadata = { title: "About", description: "Meet Rahul Kalagadda, an AI and software engineer based in Thane, India." };
export default function AboutPage() {
  return <><PageIntro number="02" label="The person behind the code" title="Always curious." italic="Always building." text="I'm Rahul Kalagadda, an engineer interested in the space between intelligent systems and the people who use them." />
    <section className="container about-story"><div className="about-identity-card"><span className="eyebrow">Hello, I&apos;m Rahul.</span><div className="identity-initials" aria-hidden="true">rk<span>.</span></div><div className="identity-caption"><span>Engineer.<br />Builder. Explorer.</span><ArrowUpRight size={35} /></div><span className="mono"><MapPin size={14} />{person.location}</span></div><div className="story-copy"><Eyebrow>A connected way of thinking</Eyebrow><h2>I like the part where<br /><span className="serif-word">ideas become real.</span></h2><p>{person.intro}</p><p>That means moving between model workflows, APIs, application state, and the interface a person actually sees. I enjoy making those pieces work together.</p><p>My GitHub is a record of that curiosity: healthcare interfaces, voice agents, CRM workflows, travel applications, and document-assistant experiments. Some are connected applications; others are prototypes that helped me explore a problem.</p><div className="action-row"><ActionLink href="/resume" primary>View my résumé</ActionLink><ActionLink href={person.github} external>GitHub profile</ActionLink></div></div></section>
    <section className="container section-pad"><div className="section-heading"><div><Eyebrow>The journey so far</Eyebrow><h2>Learning by<br /><span className="serif-word">doing the work.</span></h2></div><p className="section-heading-aside">Experience across AI workflows, product engineering, and business applications.</p></div><div className="journey-list">{journey.map((item, i) => <article key={item.period} className="journey-row"><span className="mono journey-date">{item.period}</span><div><span className="eyebrow">{item.company}</span><h3>{item.role}</h3><p>{item.text}</p></div><span className="journey-number" aria-hidden="true">0{i + 1}</span></article>)}</div><div className="education-card"><div><Eyebrow>The foundation</Eyebrow><h3>Bachelor of Computer Applications</h3><p>Chhatrapati Shivaji Maharaj University, Navi Mumbai</p></div><span className="mono">2023 — 2026</span></div></section>
    <section className="container principles-section"><Eyebrow>How I approach the work</Eyebrow><div className="principles-grid">{[{title:"Start with the problem.",text:"Understand the person, the workflow, and the constraint before choosing a tool."},{title:"Make the boundaries clear.",text:"Treat interfaces, APIs, data, and model behavior as parts of the same system."},{title:"Stay curious.",text:"Build small experiments, learn from what happens, and keep improving the details."}].map((item,i)=><article key={item.title}><span className="mono">0{i+1} /</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section><CallToAction /></>;
}
