import Link from "next/link";
import { ArrowUpRight, ChevronDown, GitBranch, Layers, Leaf, MessageSquare } from "lucide-react";
import { Eyebrow } from "./Primitives";
import { BotanicalBranch } from "./Botanical";
import { person } from "@/data/portfolio";

const notes = [
  { icon: MessageSquare, label: "AI / RETRIEVAL", title: "The answer starts before the model.", intro: "Useful context is part of the system, not an afterthought.", text: "In SevaSetu AI, chat requests carry conversation history, language, and retrieved context. Qdrant and FAISS sit behind different retrieval workflows. The design lesson: keep the boundaries visible, so a conversation, a search result, and a stored document have clear jobs.", href: "/projects/sevasetu-ai", project: "SevaSetu AI" },
  { icon: GitBranch, label: "SYSTEMS / ACCESS", title: "A session is more than a login screen.", intro: "The interface and its requests need to agree on access.", text: "EstateFlow CRM brings role guards, session handling, and a token-refresh request queue into the application. Access state affects the whole workspace, including what happens when several requests need a refreshed token at once.", href: "/projects/estateflow-crm", project: "EstateFlow CRM" },
  { icon: Leaf, label: "EXPERIENCE / RESILIENCE", title: "Offline begins while you are online.", intro: "A useful fallback depends on what was prepared earlier.", text: "SevaSetu's service worker caches static resources and the first-aid route. That makes previously cached material available when connectivity drops. It also creates a clear boundary: a page must have been cached before it can be available offline.", href: "/projects/sevasetu-ai", project: "SevaSetu AI" },
];

export function FieldNotes() {
  return <section id="field-notes" className="container section-pad field-notes"><div className="section-heading"><div><Eyebrow><span className="index-number">05 /</span>Notes from the build</Eyebrow><h2>Small decisions.<br /><span className="serif-word">Deeper roots.</span></h2></div><p className="section-heading-aside">A few engineering choices from the projects. Open a note, follow the idea, then inspect the source.</p></div><div className="field-notes-grid">{notes.map((note, i) => <article key={note.title} className="field-note"><div className="field-note-top"><note.icon size={24} strokeWidth={1.3} /><span className="mono">0{i + 1}</span></div><span className="field-note-label mono">{note.label}</span><h3>{note.title}</h3><p>{note.intro}</p><details><summary>Read the field note<ChevronDown size={16} /></summary><div><p>{note.text}</p><Link className="text-link" href={note.href}>Explore {note.project}<ArrowUpRight size={16} /></Link></div></details></article>)}</div></section>;
}

export function PortfolioQuestions() {
  return <section id="portfolio-questions" className="container section-pad portfolio-questions"><div className="portfolio-question-intro"><BotanicalBranch className="question-botanical" /><Eyebrow><span className="index-number">07 /</span>A few useful answers</Eyebrow><h2>Curious about<br /><span className="serif-word">the work?</span></h2><p>Start here, or start a conversation.</p><a href={"mailto:" + person.email} className="text-link">Let&apos;s talk<ArrowUpRight size={17} /></a></div><div className="portfolio-faq"><details><summary><span>What kinds of systems do you build?</span><ChevronDown size={19} /></summary><div><p>AI features, connected applications, and thoughtful web interfaces. The collection includes retrieval-based assistants, a voice pipeline, a CRM workspace, travel booking, and interface prototypes.</p><Link className="text-link" href="/expertise">Explore the three disciplines<ArrowUpRight size={16} /></Link></div></details><details><summary><span>Where can I inspect the implementation?</span><ChevronDown size={19} /></summary><div><p>Every case study links to its GitHub repository and explains the architecture, features, and project scope. The comparison page lets you explore several systems together.</p><Link className="text-link" href="/projects/compare">Compare projects<Layers size={16} /></Link></div></details><details><summary><span>How should I get in touch?</span><ChevronDown size={19} /></summary><div><p>Email me at <a href={"mailto:" + person.email}>{person.email}</a>, connect on LinkedIn, or use the contact page to prepare an email with your idea.</p><Link className="text-link" href="/contact">Start a conversation<ArrowUpRight size={16} /></Link></div></details></div></section>;
}
